# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6qA_bcB7hqck9yqxAlHTrI3J47OUvgl

**1) INSTALLING NECESSARY LIBRARIES**
"""

# Install required libraries
!pip install numpy pandas scikit-learn matplotlib seaborn
!pip install transformers torch shap lime

"""**2) LOADING THE DATASET**"""

import pandas as pd

# Load dataset
df = pd.read_csv("/content/Fake.csv", on_bad_lines='skip', engine="python")
df_real = pd.read_csv("/content/True.csv", on_bad_lines='skip', engine="python")

# Add labels
df['label'] = 0   # Fake
df_real['label'] = 1  # Real

# Combine datasets
data = pd.concat([df, df_real], axis=0).reset_index(drop=True)

# Shuffle
data = data.sample(frac=1).reset_index(drop=True)

print(data.head())

"""**3) PREPROCESSING**"""

from sklearn.model_selection import train_test_split
import re

# Clean text function
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # remove punctuation/numbers
    return text

# Apply cleaning
data['text'] = data['text'].apply(clean_text)

# Features and labels
X = data['text']
y = data['label']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=40
)

"""**4) EXAMINING TF-IDF VECTORIZER AND LOGISTIC REGRESSION TO FIND MODEL ACCURACY**"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Logistic Regression
model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train_tfidf, y_train)

# Predictions
y_pred_lr = model_lr.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

"""**5) DEEP - LEARNING (BERT FINE - TUNING)**"""

from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
import torch
from torch.utils.data import Dataset
import numpy as np

# Tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

class NewsDataset(Dataset):
    def __init__(self, texts, labels):
        self.encodings = tokenizer(texts.tolist(), truncation=True, padding=True, max_length=256)
        self.labels = labels.tolist()
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

train_dataset = NewsDataset(X_train, y_train)
test_dataset = NewsDataset(X_test, y_test)


# Model
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

# Training arguments (no deprecated parameters)
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    save_steps=500,
    eval_steps=500,
    logging_dir='./logs',
    logging_steps=100
)

from sklearn.metrics import precision_recall_fscore_support, accuracy_score
import numpy as np

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average='binary'
    )
    acc = accuracy_score(labels, predictions)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()
results = trainer.evaluate()
print(results)

"""## **TESTING WITH MANUAL EXAMPLES**"""

def predict_news(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=256)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    outputs = model(**inputs)
    pred = outputs.logits.argmax(dim=1).item()

    return "News is Real" if pred == 1 else "News is Fake"

print(predict_news("Breaking: Government confirms new economic policy reform"))

print(predict_news("apple kills people"))

"""## **GRAPHICAL REPRESENTATION**"""

import matplotlib.pyplot as plt

# Logistic Regression accuracy
lr_accuracy = accuracy_score(y_test, y_pred_lr)

# BERT accuracy
bert_accuracy = results['eval_accuracy']

models = ['Logistic Regression', 'BERT']
accuracies = [lr_accuracy, bert_accuracy]

plt.figure()
plt.bar(models, accuracies)
plt.ylabel('Accuracy')
plt.title('Accuracy Comparison (LR vs BERT)')

for i, v in enumerate(accuracies):
    plt.text(i, v, f"{v:.4f}", ha='center')

plt.show()

# Logistic Regression metrics
from sklearn.metrics import precision_score, recall_score, f1_score

lr_precision = precision_score(y_test, y_pred_lr)
lr_recall = recall_score(y_test, y_pred_lr)
lr_f1 = f1_score(y_test, y_pred_lr)

# BERT metrics (from results)
bert_precision = results['eval_precision']
bert_recall = results['eval_recall']
bert_f1 = results['eval_f1']

labels = ['Precision', 'Recall', 'F1-score']
x = range(len(labels))

plt.figure()

plt.bar(x, [lr_precision, lr_recall, lr_f1], width=0.4, label='Logistic Regression')
plt.bar([i + 0.4 for i in x], [bert_precision, bert_recall, bert_f1], width=0.4, label='BERT')

plt.xticks([i + 0.2 for i in x], labels)
plt.ylabel('Score')
plt.title('Precision, Recall, F1-score Comparison')
plt.legend()

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm_lr = confusion_matrix(y_test, y_pred_lr)

plt.figure()
sns.heatmap(cm_lr, annot=True, fmt='d', xticklabels=['Fake', 'Real'], yticklabels=['Fake', 'Real'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Logistic Regression')
plt.show()

# Get predictions from BERT
predictions = trainer.predict(test_dataset)
y_pred_bert = predictions.predictions.argmax(axis=1)

cm_bert = confusion_matrix(y_test, y_pred_bert)

plt.figure()
sns.heatmap(cm_bert, annot=True, fmt='d', xticklabels=['Fake', 'Real'], yticklabels=['Fake', 'Real'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - BERT')
plt.show()